name: flutter_firestore_todos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shop_repository:
    path: shop_repository
  todos_repository:
    path: todos_repository
  user_repository:
    path: user_repository
  carousel_slider: ^2.1.0
  equatable: ^1.2.5
  eva_icons_flutter: ^2.0.1
  fancy_shimmer_image: ^1.2.0
  firebase_storage: ^5.2.0
  flutter_bloc: ^6.1.1
  flutter_facebook_auth: ^1.0.2+2
  flutter_keyboard_visibility: ^2.0.0
  flutter_page_indicator: ^0.0.3
  flutter_staggered_grid_view: ^0.3.3
  flutter_svg: ^0.19.1
  flutter_swiper: ^1.1.6
  google_fonts: ^1.1.0
  google_sign_in: ^4.5.1
  image_stack: ^1.1.0
  md2_tab_indicator: ^1.0.2
  photo_manager: ^0.5.8
  photo_view: ^0.10.3
  rules: ^1.2.0+3

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AdobeClean-Bold
      fonts:
        - asset: fonts/AdobeClean-Bold.ttf
    - family: AdobeClean-Regular
      fonts:
        - asset: fonts/AdobeClean-Regular.ttf
    - family: VarelaRound-Regular
      fonts:
        - asset: fonts/VarelaRound-Regular.ttf
