name: flutter_firestore_todos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  todos_repository:
    path: todos_repository
  user_repository:
    path: user_repository
  shop_repository:
    path: shop_repository
  equatable: ^1.0.0 
  flutter_svg: ^0.17.4
  eva_icons_flutter:
  flutter_staggered_grid_view: ^0.2.7
  flutter_swiper: ^1.1.6
  flutter_page_indicator: ^0.0.3
  fancy_shimmer_image: ^1.0.1
  photo_view: ^0.9.2
  carousel_slider: ^2.1.0
  google_fonts: ^1.1.0
  flutter_keyboard_visibility: ^2.0.0
  lottie: ^0.3.6
  photo_manager: ^0.5.3
  md2_tab_indicator: ^1.0.2
  image_stack: ^1.1.0
  rules: ^1.0.2+1
  google_sign_in: ^4.5.1
  flutter_facebook_auth: ^0.2.3
  firebase_storage: ^3.1.1

flutter:
  uses-material-design: true
  assets:
  - assets/
  fonts:
  - family: AdobeClean-Bold
    fonts:
      - asset: fonts/AdobeClean-Bold.ttf
  - family: AdobeClean-Regular
    fonts:
      - asset: fonts/AdobeClean-Regular.ttf
  - family: VarelaRound-Regular
    fonts:
      - asset: fonts/VarelaRound-Regular.ttf