name: user_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  flutter_facebook_auth: ^0.2.3
  equatable: ^1.2.0