name: user_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  equatable: ^1.2.0
  firebase_auth: ^0.18.4+1
  flutter_facebook_auth: ^1.0.2+2
  google_sign_in: ^4.5.1
