name: shop_repository

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.1
  equatable: ^1.2.0
  photo_manager: ^0.5.3